/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthcheck": {
    /** ヘルスチェック */
    post: operations["healthcheck"];
  };
  "/users/{userId}/murmurs/": {
    /** 自分のつぶやきとフォローしているつぶやき一覧を取得する。 */
    get: operations["getMurmurs"];
    /** 自分のつぶやきを登録する。 */
    post: operations["createMurmur"];
  };
}

export interface components {
  schemas: {
    Ping: {
      ping: boolean;
    };
    Pong: {
      message: string;
    };
    Murmur: {
      id: number;
      text: string;
      postUserId: number;
      postUserName: string;
      createdAt: string;
      updatedAt: string;
    };
    CreateMurmur: {
      text: string;
    };
  };
  responses: {
    /** pong */
    ResHealthcheck: {
      content: {
        "application/json": components["schemas"]["Pong"][];
      };
    };
    /** getMurmursResponse */
    ResGetMurmurs: {
      content: {
        "application/json": components["schemas"]["Murmur"][];
      };
    };
  };
}

export interface operations {
  /** ヘルスチェック */
  healthcheck: {
    responses: {
      200: components["responses"]["ResHealthcheck"];
    };
    /** ping */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ping"];
      };
    };
  };
  /** 自分のつぶやきとフォローしているつぶやき一覧を取得する。 */
  getMurmurs: {
    parameters: {
      path: {
        userId: number;
      };
    };
    responses: {
      200: components["responses"]["ResGetMurmurs"];
    };
  };
  /** 自分のつぶやきを登録する。 */
  createMurmur: {
    parameters: {
      path: {
        userId: number;
      };
    };
    responses: {
      /** Created */
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMurmur"];
      };
    };
  };
}

export interface external {}
